# Generated by Django 3.1.6 on 2021-05-02 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='resource_entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=400)),
                ('image', models.CharField(max_length=100)),
                ('links', models.CharField(max_length=100)),
                ('resource', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('added_on', models.CharField(max_length=100)),
                ('rating', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100)),
            ],
        ),
    ]
