# Generated by Django 3.1.6 on 2021-05-02 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20210502_1931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource_entry',
            old_name='location',
            new_name='city',
        ),
    ]
