# Generated by Django 3.1.6 on 2021-05-02 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20210502_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource_entry',
            name='contact',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='resource_entry',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='resource_entry',
            name='links',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='resource_entry',
            name='rating',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='resource_entry',
            name='source',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
