# Generated by Django 3.1.6 on 2021-05-03 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20210502_1940'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='resource_entry',
            table='resource_entryr',
        ),
    ]
