# Generated by Django 3.1.6 on 2021-05-03 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20210503_1033'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='resource_entry',
            table='resource_entry',
        ),
    ]
