# Generated by Django 3.1.6 on 2021-05-03 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20210503_1033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource_entry',
            name='id',
        ),
        migrations.AlterField(
            model_name='resource_entry',
            name='contact',
            field=models.CharField(blank=True, max_length=100, primary_key=True, serialize=False),
        ),
    ]
