# Generated by Django 3.1.6 on 2021-05-03 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20210503_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource_entry',
            name='contact',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
